on:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: "ubuntu-latest"
    seps:
      - name: test
        run: echo "You may implement your tests here"

  ci_pass:
    if: ${{ always() }}
    runs-on: "ubuntu-latest"
    steps:
      - name: check status
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}